import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Footer } from "../src/components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ken's link 🐱</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Ken's link ! 😸</h1>

        {/* <p className={styles.description}>
          Hi, I'm a Developer, designer, photographer, and musician 🧑🏻‍💻
        </p> */}

        <div className={styles.grid}>
          <a
            href="https://twitter.com/ken_tsx"
            //  className={styles.card}
            className={styles.card}
          >
            <Image
              className={styles.image}
              src="/twitter.svg"
              alt="twetter Logo"
              // width={72} height={16}
              width={25}
              height={25}
            />
            <h2>Twitter</h2>
            {/* <p>FI.</p> */}
          </a>

          <a
            href="https://twitter.com/ken_tsx"
            //  className={styles.card}
            className={styles.card}
          >
            <Image
              className={styles.image}
              src="/twitter.svg"
              alt="twetter Logo"
              // width={72} height={16}
              width={25}
              height={25}
            />
            <h2>Twitter</h2>
            {/* <p>FI.</p> */}
          </a>
          <a
            href="https://twitter.com/ken_tsx"
            //  className={styles.card}
            className={styles.card}
          >
            <Image
              className={styles.image}
              src="/twitter.svg"
              alt="twetter Logo"
              // width={72} height={16}
              width={25}
              height={25}
            />
            <h2>Twitter</h2>
            {/* <p>FI.</p> */}
          </a>
        </div>

        {/* </div> */}
      </main>
      <Footer />
    </div>
  );
}
